services: 
        studentapp: 
            build: ./studentapp
            ports:
                - "8080:8080" 
        sampledockerfile: 
            build: ./sampledockerfile
            ports:
                - "80:80"
        Todo-App-React-FE-Node.js-BE-MySQL-Docker: 
            build: ./Todo-App-React-FE-Node.js-BE-MySQL-Docker/todo-app/frontend
            ports:
                - "5000:5000"