services: 
        studentapp: 
            build: ./studentapp
            ports:
                - "8080:8080" 
        sampledockerfile: 
            build: ./sampledockerfile
            ports:
                - "80:80"
        todo-app: 
            build:
            context: ./frontend
            ports:
                - "5000:5000"