services: 
        studentapp: 
            build: ./studentapp
            ports:
                - "8080:8080" 
        sampledockerfile: 
            build: ./sampledockerfile
            ports:
                - "80:80"
        todo-app: 
            build: ./todo-app/frontend
            ports:
                - "5000:5000"
   #         depends_on:
    #            - backend
        
     #   backend:
      #      build: ./todo-app/backend
       #     ports:
        #        - "3001-3001"