services: 
        studentapp: 
            build: ./studentapp
            ports:
                - "8080:8080" 
        sampledockerfile: 
            build: ./sampledockerfile
            ports:
                - "80:80"
        frontend: 
            build: ./todo-app/frontend
            ports:
                - "3000:80"
            depends_on:
                - backend
        
        backend:
            build: ./todo-app/backend
            ports:
                - "3001-3001"