services: 
        studentapp: 
            build: ./studentapp
            ports:
                - "8080:8080" 
        sampledockerfile: 
            build: ./sampledockerfile
            ports:
                - "80:80"
        todo-app: 
            build:
            context: ./todo-app
            dockerfile: /todo-app/frontend/Dockerfile.dev
            ports:
                - "5000:5000"