services: 
        studentapp: 
            build: ./studentapp
            ports:
                - "8080:8080" 
        sampledockerfile: 
            build: ./sampledockerfile
            ports:
                - "5000:5000"
        todo-app: 
            build: ./todo-app
            ports:
                - "80:80"