apiVersion: v1
kind: Pod
metadata:
  name:  my-podci
  labels:
    app: my-podci
spec:
  containers:
    - image:  nginx
      name:  my-nginx-pod
      ports:
        - containerPort:  80

---

apiVersion: v1
kind: Service
metadata:
  name:  my-svcci
spec:
  selector:
    app:  my-podci
  type: ClusterIP
  ports:
  - protocol: TCP
    port:  80
    targetPort:  8080