apiVersion: v1
kind: Pod
metadata:
  name:  my-podnp
  labels:
    app: my-podnp
spec:
  containers:
    - image:  nginx
      name:  my-podnp
      ports:
        - containerPort:  80

---

apiVersion: v1
kind: Service
metadata:
  name:  my-svcnp
spec:
  selector:
    app:  my-podnp
  type: NodePort
  ports:
  - protocol: TCP
    port:  80
    targetPort:  8080
    nodePort: 30600