apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replica: 5
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image:  nginx
          name:  nginx-rc
          ports:
            - containerPort: 80